import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Theme>
					<main className="flex flex-col items-center min-h-screen bg-background">
						{children}
					</main>
				</Theme>
			</body>
		</html>
	);
}
